# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "boa-ideas-home-assignment"
client_id = "4e083a15aef0437f5db3a91e605ba66a"
application_url = "https://asn-advertisements-oil-packet.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers"

[auth]
redirect_urls = [
  "https://asn-advertisements-oil-packet.trycloudflare.com/auth/callback",
  "https://asn-advertisements-oil-packet.trycloudflare.com/auth/shopify/callback",
  "https://asn-advertisements-oil-packet.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "home-assignment-21.myshopify.com"
